### ISSUE TITLE
Automatically deploy mock server based on API specification.

### ISSUE THREAD

**Issue by noratanX** [SandorBalazsHU/elte-ik-msc-weather-cam#11]
I found a tool that can mock our API based on the specification.
This tool is called [Prism](https://github.com/stoplightio/prism). The only problem is that it uses NodeJs so I cannot upload it to our mock server (I think). If we could make it that our CI/CD pipeline would pick up changes to the [specification file](https://github.com/SandorBalazsHU/elte-ik-msc-weather-cam/blob/main/Documentation/WebApi/weather-cam-web-api.yaml) and run Prism to host that would make our lives a lot easier.

### Installation

_Prism requires NodeJS >= 16 to properly work._

```bash
npm install -g @stoplight/prism-cli

# OR

yarn global add @stoplight/prism-cli
```

### How to start mocking

Prism can help you create a fake "mock" based off an OpenAPI document, which helps people see how your API will work before you even have it built. Run it locally with the `prism mock` command to run your API on a HTTP server you can interact with.

```bash
prism mock https://raw.githubusercontent.com/SandorBalazsHU/elte-ik-msc-weather-cam/main/Documentation/WebApi/weather-cam-web-api.yaml
```
Learn more about [how the mock server works](docs/guides/01-mocking.md).

**Comment by MarcellHarmaci** [comment]
While you guys sort this out I implemented the basic mock PHP endpoints and uploaded them to the server under `mock.weather` for a start. (related PR #12)
You can find more info [here in the API wiki](https://github.com/SandorBalazsHU/elte-ik-msc-weather-cam/wiki/Web-API).

**Comment by ladobence** [comment]
vm_weather@weather-cicd:~$ prism mock https://raw.githubusercontent.com/SandorBalazsHU/elte-ik-msc-weather-cam/main/Documentation/WebApi/weather-cam-web-api.yaml
Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.call (/usr/local/lib/node_modules/@stoplight/prism-cli/node_modules/micri/webpack:/micri/external node-commonjs "worker_threads":1:1)
    at __webpack_require__ (/usr/local/lib/node_modules/@stoplight/prism-cli/node_modules/micri/webpack:/micri/webpack/bootstrap:21:1)
    at Object.call (/usr/local/lib/node_modules/@stoplight/prism-cli/node_modules/micri/webpack:/micri/src/with-worker.ts:8:1)
    at __webpack_require__ (/usr/local/lib/node_modules/@stoplight/prism-cli/node_modules/micri/webpack:/micri/webpack/bootstrap:21:1)
    at Object.call (/usr/local/lib/node_modules/@stoplight/prism-cli/node_modules/micri/webpack:/micri/src/index.ts:36:1)
    at __nccwpck_require__ (/usr/local/lib/node_modules/@stoplight/prism-cli/node_modules/micri/webpack:/micri/webpack/bootstrap:21:1)
